<a href="https://colab.research.google.com/github/RamshaArshad1/Python/blob/main/ML_Model_1st.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Uploading and cleaning data**

In [20]:
#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
#upload data set
from google.colab import files
uploaded=files.upload()

Saving marketing_campaign.csv to marketing_campaign (2).csv

In [24]:
#Load data set
df=pd.read_csv("marketing_campaign (2).csv")
df

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138,0,0,9/4/2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344,1,1,3/8/2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613,0,0,8/21/2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646,1,0,2/10/2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293,1,0,1/19/2014,94,173,...,5,0,0,0,0,0,0,3,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2211,10870,1967,Graduation,Married,61223,0,1,6/13/2013,46,709,...,5,0,0,0,0,0,0,3,11,0
2212,4001,1946,PhD,Together,64014,2,1,6/10/2014,56,406,...,7,0,0,0,1,0,0,3,11,0
2213,7270,1981,Graduation,Divorced,56981,0,0,1/25/2014,91,908,...,6,0,1,0,0,0,0,3,11,0
2214,8235,1956,Master,Together,69245,0,1,1/24/2014,8,428,...,3,0,0,0,0,0,0,3,11,0
2215,9405,1954,PhD,Married,52869,1,1,10/15/2012,40,84,...,7,0,0,0,0,0,0,3,11,1

In [27]:
#check the number of column and rows
rows = len(df.axes[0])
columns = len(df.axes[1])
print(df)
print("Number of Rows: ", rows)
print("Number of Columns: ", columns)

         ID  Year_Birth   Education Marital_Status  Income  Kidhome  Teenhome  \
0      5524        1957  Graduation         Single   58138        0         0
1      2174        1954  Graduation         Single   46344        1         1
2      4141        1965  Graduation       Together   71613        0         0
3      6182        1984  Graduation       Together   26646        1         0
4      5324        1981         PhD        Married   58293        1         0
...     ...         ...         ...            ...     ...      ...       ...
2211  10870        1967  Graduation        Married   61223        0         1
2212   4001        1946         PhD       Together   64014        2         1
2213   7270        1981  Graduation       Divorced   56981        0         0
2214   8235        1956      Master       Together   69245        0         1
2215   9405        1954         PhD        Married   52869        1         1

     Dt_Customer  Recency  MntWines  ...  NumWebVisitsMonth  AcceptedCmp3  \
0       9/4/2012       58       635  ...                  7             0
1       3/8/2014       38        11  ...                  5             0
2      8/21/2013       26       426  ...                  4             0
3      2/10/2014       26        11  ...                  6             0
4      1/19/2014       94       173  ...                  5             0
...          ...      ...       ...  ...                ...           ...
2211   6/13/2013       46       709  ...                  5             0
2212   6/10/2014       56       406  ...                  7             0
2213   1/25/2014       91       908  ...                  6             0
2214   1/24/2014        8       428  ...                  3             0
2215  10/15/2012       40        84  ...                  7             0

      AcceptedCmp4  AcceptedCmp5  AcceptedCmp1  AcceptedCmp2  Complain  \
0                0             0             0             0         0
1                0             0             0             0         0
2                0             0             0             0         0
3                0             0             0             0         0
4                0             0             0             0         0
...            ...           ...           ...           ...       ...
2211             0             0             0             0         0
2212             0             0             1             0         0
2213             1             0             0             0         0
2214             0             0             0             0         0
2215             0             0             0             0         0

      Z_CostContact  Z_Revenue  Response
0                 3         11         1
1                 3         11         0
2                 3         11         0
3                 3         11         0
4                 3         11         0
...             ...        ...       ...
2211              3         11         0
2212              3         11         0
2213              3         11         0
2214              3         11         0
2215              3         11         1

[2216 rows x 29 columns]
Number of Rows:  2216
Number of Columns:  29

# EDA (Exploratory Data Analysis)